#开发环境
server:
  port: 8203
  context-path: /app-login
spring:
  datasource:
    username: zyq
    password: zyq
    url: jdbc:mysql://172.16.0.197:3306/zyq_rbac?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句。
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters
    filters: stat
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.scsc.rbac.entity

#showSql

logging:
  level:
    com:
      scsc:
        rbac:
          mapper: debug

